name: academia-financas-para-propositos

services:
  front-end-app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 3072M
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
    user: node
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
